softcomputacion/Models/venta.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace softcomputacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public venta()
        {
            this.detalleVenta = new HashSet<detalleVenta>();
            this.detallePago = new HashSet<detallePago>();
        }
    
        public int idVenta { get; set; }
        public System.DateTime fechaEmision { get; set; }
        public int idUsuario { get; set; }
        public decimal costoTotal { get; set; }
        public int cantidadProductosTotal { get; set; }
        public Nullable<int> idCliente { get; set; }
        public int idEstado { get; set; }
        public decimal entregado { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleVenta> detalleVenta { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallePago> detallePago { get; set; }
        public virtual estado estado { get; set; }
    }
}

softcomputacion/Controllers/VentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using softcomputacion.Models;
using softcomputacion.Servicios;
using PagedList;
using System.Web.Mvc;

namespace softcomputacion.Controllers
{
    public class VentaController : Controller
    {
        
        public ActionResult NuevaVenta(int nroPagina = 1, int tamañoPagina = 6, bool paginacion = false)
        {
            try
            {
                usuario oUsuario = (usuario)Session["Usuario"];
                if (oUsuario == null)
                {
                    Session.Clear();
                    return RedirectToAction("Index", "Home");
                }
                srvEstado sEstado = new srvEstado();
                srvProducto sProducto = new srvProducto();
                srvCategoria sCategoria = new srvCategoria();
                List<producto> lstProductos = (List<producto>)Session["lstProducto"];
                if (lstProductos == null || lstProductos.Count == 0 || paginacion == false)
                {
                    Session["lstProducto"] = new List<producto>();
                    lstProductos = new List<producto>();
                }
                if (Session["venta"] == null)
                {
                    Session["venta"] = new venta();
                }
                ViewBag.lstCategorias = sCategoria.ObtenerCategorias();
                ViewBag.lstEstados = sEstado.ObtenerEstados("VENTA");
                ViewBag.filtros = ";;;";
                ProductoController ProductoController = new ProductoController();
                ViewBag.ValorUSD = ProductoController.GetValorUsd();
                PagedList<producto> model = new PagedList<producto>(lstProductos.ToList(), nroPagina, tamañoPagina);
                return View(model);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error", new { stError = "Se produjo un error al intentar obtener los datos del servidor." });
            }

        }
        [HttpPost]
        public ActionResult NuevaVenta(string nombreProducto = "", int idEstado = 0, int idCategoria = 0, int idSubCategoria = 0, int idProducto = 0)
        {
            try
            {
                usuario oUsuario = (usuario)Session["Usuario"];
                if (oUsuario == null)
                {
                    Session.Clear();
                    return RedirectToAction("Index", "Home");
                }
                if (Session["venta"] == null)
                {
                    Session["venta"] = new venta();
                }
                srvEstado sEstado = new srvEstado();
                srvProducto sProducto = new srvProducto();
                srvCategoria sCategoria = new srvCategoria();
                List<producto> lstProductos = sProducto.ObtenerProductos(nombreProducto, idCategoria, idSubCategoria, idEstado, idProducto);
                Session["lstProducto"] = lstProductos;
                ViewBag.lstCategorias = sCategoria.ObtenerCategorias();
                ViewBag.lstEstados = sEstado.ObtenerEstados("PRODUCTO");
                ViewBag.filtros = Convert.ToString(nombreProducto + ";" + idCategoria + ";" + idSubCategoria + ";" + idEstado);
                ProductoController ProductoController = new ProductoController();
                ViewBag.ValorUSD = ProductoController.GetValorUsd();
                PagedList<producto> model = new PagedList<producto>(lstProductos.ToList(), 1, 6);
                return View(model);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error", new { stError = "Se produjo un error al intentar obtener los datos del servidor." });
            }

        }
        public ActionResult VistaVenta(int idVenta)
        {
            try
            {
                usuario oUsuario = (usuario)Session["Usuario"];
                if (oUsuario == null)
                {
                    Session.Clear();
                    return RedirectToAction("Index", "Home");
                }
                
                srvVenta sVenta = new srvVenta();
                srvMetodoPago sMetodoP = new srvMetodoPago();
                venta oVenta = sVenta.ObtenerVenta(idVenta);
                ViewBag.metodosPago = sMetodoP.ObtenerMetodosPago();
                ViewBag.detallesPago = sVenta.ObtenerDetallesPagoDeVenta(idVenta);
                if (oVenta.idCliente==0 || oVenta.idCliente == null)
                {
                    oVenta.idCliente = 0;
                    oVenta.cliente = new cliente();
                    oVenta.cliente.nombre = "CONSUMIDOR ";
                    oVenta.cliente.apellido = "FINAL";
                }
                return View(oVenta);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error", new { stError = "Se produjo un error al intentar obtener los datos del servidor." });
            }
        }
        public ActionResult ListarVentas(int nroPagina = 1, int tamañoPagina = 10, bool paginacion = false)
        {
            try
            {
                usuario oUsuario = (usuario)Session["Usuario"];
                if (oUsuario == null)
                {
                    Session.Clear();
                    return RedirectToAction("Index", "Home");
                }
                srvUsuario sUsuario = new srvUsuario();
                ViewBag.Ususarios = sUsuario.ObtenerUsuarios();
                List<venta> lstVentas= (List<venta>)Session["lstVentas"];
                if (lstVentas == null || lstVentas.Count == 0 || paginacion == false)
                {
                    srvVenta sVenta = new srvVenta();
                    lstVentas = sVenta.ObtenerVentas(Convert.ToDateTime("01/01/1000"), Convert.ToDateTime("01/01/3000"), oUsuario.idUsuario);
                    Session["lstVentas"] = lstVentas;
                }
                ViewBag.filtros = ";;";
                PagedList<venta> ModelVentas = new PagedList<venta>(lstVentas.ToList(), nroPagina, tamañoPagina);
                return View(ModelVentas);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error", new { stError = "Se produjo un error al intentar obtener los datos del servidor." });
            }
        }
        [HttpPost]
        public ActionResult ListarVentas(string fechaDesde, string fechaHasta, int idUsuario = 0, int idVenta=0)
        {
            ViewBag.filtros = fechaDesde + ";" + fechaHasta + ";" + idUsuario;
            if (fechaDesde == "") fechaDesde = "01/01/1000";
            if (fechaHasta == "") fechaHasta = "01/01/3000";
            try
            {                
                usuario oUsuario = (usuario)Session["Usuario"];
                if (oUsuario == null)
                {
                    Session.Clear();
                    return RedirectToAction("Index", "Home");
                }
                srvVenta sVenta = new srvVenta();
                List<venta> lstVentas;
                srvUsuario sUsuario = new srvUsuario();
                ViewBag.Ususarios = sUsuario.ObtenerUsuarios();
                lstVentas = sVenta.ObtenerVentas(Convert.ToDateTime(fechaDesde), Convert.ToDateTime(fechaHasta),idUsuario, idVenta);
                Session["lstVentas"] = lstVentas;
                PagedList<venta> ModelVentas = new PagedList<venta>(lstVentas.ToList(), 1, 10);
                return View(ModelVentas);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error", new { stError = "Se produjo un error al intentar obtener los datos del servidor." });
            }
        }

        //Vistas Parciales
        [HttpPost]
        public PartialViewResult _CarritoVenta(int idProducto, string precio, string cantidad)
        {
            decimal precioD = Convert.ToDecimal(precio);
            int cantidadI = Convert.ToInt32(cantidad);
            try
            {
                venta oVenta = new venta();
                if (Session["venta"] == null)
                {
                    Session["venta"] = new venta();
                }
                else
                {
                    //Session["venta"] = Session["venta"];
                    oVenta = (venta)Session["venta"];
                }
                srvVenta sVenta = new srvVenta();
                oVenta = sVenta.agregarDetalle(oVenta, idProducto, precioD, cantidadI);
                Session["venta"] = oVenta;
                return PartialView();
            }
            catch (Exception)
            {
                return null;
            }
        }

        //Metodos
        public string borrarDetalle(int idProducto)
        {
            try
            {
                venta oVenta = new venta();
                oVenta = (venta)Session["venta"];
                detalleVenta oDetalle = new detalleVenta();
                oDetalle = oVenta.detalleVenta.Where(x => x.idProducto == idProducto).First();                
                oVenta.detalleVenta.Remove(oDetalle);
                return "true";
            }
            catch (Exception)
            {
                return "false";
            }
        }
        [HttpPost]
        public ActionResult GenerarVenta()
        {
            try
            {
                Session["lstProducto"] = null;
                usuario oUsuario = (usuario)Session["Usuario"];
                if (oUsuario == null)
                {
                    Session.Clear();
                    return RedirectToAction("Index", "Home");
                }
                venta oVenta = (venta)Session["venta"];

                oVenta.cliente = null;
                oVenta.idUsuario = oUsuario.idUsuario;
                oVenta.entregado = 0;
                oVenta.idEstado = 9;
                srvVenta sVenta = new srvVenta();                

softcomputacion/Views/Venta/ListarVentas.cshtml
@{
    ViewBag.Title = "Listar ventas";
    Layout = "~/Views/Shared/_UsuarioLogueado.cshtml";
    softcomputacion.Models.usuario oUsuario = (softcomputacion.Models.usuario)Session["Usuario"];
    List<softcomputacion.Models.usuario> lstUsuario = (List<softcomputacion.Models.usuario>)ViewBag.Ususarios;
    // 0-fechaDesde 1-fechaHasta 2-idUsuario
    string[] filtros = ViewBag.filtros.Split(';');
    if (filtros[0] != "")
    {
        DateTime fDesde = Convert.ToDateTime(filtros[0]);
        filtros[0] = fDesde.Day.ToString().PadLeft(2, '0') + "/" + fDesde.Month.ToString().PadLeft(2, '0') + "/" + fDesde.Year.ToString();
    }
    if (filtros[1] != "")
    {
        DateTime fHasta = Convert.ToDateTime(filtros[1]);
        filtros[1] = fHasta.Day.ToString().PadLeft(2, '0') + "/" + fHasta.Month.ToString().PadLeft(2, '0') + "/" + fHasta.Year.ToString();
    }

}
@model PagedList.IPagedList<softcomputacion.Models.venta>
@using PagedList.Mvc;

<br />
<br />
<div class="container-fluid">
    <div class="row">
        <div class="col-12 text-center">
            <h2>Ventas</h2>
        </div>
    </div>
    <hr style="border-top: 2px solid #b5262a;" />

    <div class="row">
        <div class="col-12 col-lg-12">
            <div class="row">
                <div class="col-12 offset-xl-1 col-xl-10">
                    @* Form de busqueda *@
                    <form method="post" action="@Url.Action("ListarVentas", "Venta")" autocomplete="off">
                        <div class="row">
                            <div class="col-12 col-md-3 col-lg-2">
                                <div class="wrap-input100 m-b-20">
                                    <input class="input100" type="text" name="idVenta" id="codigo" placeholder="Código" value="@filtros[0]">
                                </div>
                            </div>


                            <div class="col-12 col-md-3 col-lg-3">
                                <div class="wrap-input100 m-b-20">
                                    <input class="input100" type="text" name="fechaDesde" id="dpfechaDesde" placeholder="Fecha desde" value="@filtros[0]" onfocus="(this.type='date')">
                                </div>
                            </div>
                            <div class="col-12 col-md-3 col-lg-3">
                                <div class="wrap-input100 m-b-20">
                                    <input class="input100" type="text" name="fechaHasta" id="dpfechaHasta" placeholder="Fecha hasta" value="@filtros[1]" onfocus="(this.type='date')">
                                </div>
                            </div>

                            <div class="col-12 col-md-3 col-lg-3">
                                <div class="wrap-input100 ¡ m-b-20" data-validate="">
                                    <select id="select-Usuario" class="form-control input100" style="border:0px; height: 55px;" name="idUsuario">
                                        <option selected value="0">Usuario</option>

                                        @foreach (softcomputacion.Models.usuario oUsu in lstUsuario)
                                        {
                                            if (oUsu.idUsuario.ToString() == filtros[2])
                                            {
                                                <option selected value="@oUsu.idUsuario">@oUsu.apellido, @oUsu.nombre</option>
                                            }
                                            else
                                            {
                                                <option value="@oUsu.idUsuario">@oUsu.apellido, @oUsu.nombre</option>
                                            }

                                        }
                                    </select>
                                </div>
                            </div>


                            <div class="col-12 col-md-12 col-lg-1">
                                <div class="container-login100-form-btn m-b-20">
                                    <button class="login100-form-btn fs-22" style="height:56px;" type="submit">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>



            <hr style="border-top: 1px solid #b5262a;" />
            <br />
        </div>
        <div class="row container-fluid">
            <!--Lista de Productos-->
            <div class="m-b-15 col-12 offset-xl-1 col-xl-10">
                @{
                    string stFechaHs = "";
                    string stTotal = "";
                    foreach (var oVenta in Model)
                    {
                        stFechaHs = oVenta.fechaEmision.Day.ToString().PadLeft(2, '0') + "/" + oVenta.fechaEmision.Month.ToString().PadLeft(2, '0') + "/" + oVenta.fechaEmision.Year + " " + oVenta.fechaEmision.Hour.ToString().PadLeft(2, '0') + ":" + oVenta.fechaEmision.Minute.ToString().PadLeft(2, '0');
                        stTotal = Convert.ToString(Math.Round(oVenta.costoTotal, 0)).Replace(",", ".").Replace(",00", "");
                <div class="row">
                    <div class="col-12 p-b-5 p-t-10 item-lista-venta" style="text-align:left;" onclick="window.open('@Url.Action("VistaVenta","Venta", new { idVenta = oVenta.idVenta })')">
                        <div class="row">

                            <div class="col-12 col-sm-3 col-md-2 col-lg-2 col-xl-2 p-l-5 p-r-5">
                                <p class="login100-form-title fs-18 p-l-5 text-center text-sm-left">
                                    <span>Nro: @oVenta.idVenta</span>
                                </p>
                            </div>
                            <div class="col-12 col-sm-6 col-md-5 col-lg-5 col-xl-5 p-l-5 p-r-5">
                                <p class="login100-form-title fs-18 p-l-5 text-center text-sm-left">
                                    @if (oVenta.idCliente != 0 && oVenta.idCliente != null)
                                    {
                                        <span>@oVenta.cliente.apellido, @oVenta.cliente.nombre</span>
                                    }
                                    else
                                    {
                                        <span>Consumidor Final</span>
                                    }

                                </p>
                            </div>
                            <div class="col-12 col-sm-3 col-md-3 col-lg-3 col-xl-3 p-l-5 p-r-5">
                                <p class="login100-form-title fs-18 p-l-5 text-center">
                                    <span>@stFechaHs</span>
                                </p>
                            </div>
                            <div class="col-12 col-sm-12 col-md-2 col-lg-2 col-xl-2 p-l-5 p-r-5">
                                <p class="login100-form-title fs-18 p-l-5 text-center text-lg-right">
                                    <span><precio class="text-primary">$ARS</precio>@stTotal</span>
                                </p>
                            </div>
                            <div class="col-12">
                                <p class="text-center text-sm-left @softcomputacion.Servicios.clsMetodosGenericos.ObtenerColorEstadoVenta(oVenta.idEstado) text-uppercase"><strong>@oVenta.estado.nombre</strong></p>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-12">
                        <hr class="m-t-0 m-b-0" />
                    </div>
                </div>
                    }
                }
            </div>
        </div>
        <div class="row container-fluid text-center">
                <div id="div-paginacion" class="col-12">
                    @Html.PagedListPager(Model, nroPagina => Url.Action("ListarVentas", "Venta", new { nroPagina, tamañoPagina = Model.PageSize, paginacion = true }), new PagedListRenderOptions() { ClassToApplyToFirstListItemInPager = null, ClassToApplyToLastListItemInPager = null, UlElementClasses = new[] { "pagination", "justify-content-center" }, LiElementClasses = new[] { "page-item" } })
                </div>
                <div class="col-12">
                    @Model.FirstItemOnPage a @Model.LastItemOnPage ventas de un total de @Model.TotalItemCount ventas.
                </div>
            </div>
    </div>
</div>

softcomputacion/Views/Venta/_CarritoVenta.cshtml
@{
    softcomputacion.Models.venta oVenta = (softcomputacion.Models.venta)Session["venta"];
    double total = 0;
    if (oVenta.cliente==null)
    {
        oVenta.idCliente = 0;
        oVenta.cliente = new softcomputacion.Models.cliente();
        oVenta.cliente.nombre = "FINAL";
        oVenta.cliente.apellido = "CONSUMIDOR";
    }
}

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <p class="text-center fs-20"><i class="fas fa-shopping-cart fs-24"></i> PRODUCTOS</p>
        </div>

    </div>
    <hr style="border-top: 1px solid #b5262a; margin-top:5px;" />
    @if (oVenta != null)
    {
        foreach (softcomputacion.Models.detalleVenta oDetalle in oVenta.detalleVenta)
        {
            total = total + Convert.ToDouble(oDetalle.costoGrupal);
            <div id="divRow">
                <div class="row" id="div-carrito-@oDetalle.idProducto">
                    <div class="col-12 col-md-10 col-lg-10">
                        <div class="row">
                            <div class="col-12 col-md-12">
                                <p class="fs-18" style="color:#000"><strong>@oDetalle.producto.categoria.nombre @oDetalle.producto.subcategoria.nombre @oDetalle.producto.nombre</strong></p>
                            </div>
                            <div class="col-6 col-sm-6 col-md-6 p-l-5 p-r-5 text-center">
                                <p class="fs-14">Cantidad: <i id="i-cant-@oDetalle.idProducto">@oDetalle.cantidad</i></p>
                            </div>
                            <div class="col-6 col-sm-6 col-md-6 p-l-5 p-r-5 text-right">
                                <p class="fs-14">P/Unit: $@Math.Round(oDetalle.costoIndividual, 0)</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-12 col-md-2 col-lg-2 p-l-0 p-r-0 text-center">
                        <p class="fs-20" style="color:#000">*$ <i id="iCostoGrupal-@oDetalle.idProducto">@Math.Round(oDetalle.costoGrupal,0)</i> </p>
                    </div>
                    <div class="col-12">
                        <div class="clearfix">
                            @if (oDetalle.producto.garantia == "" || oDetalle.producto.garantia == null)
                            {
                                <p class="fs-14 float-left">Gtia: N/A</p>
                            }
                            else
                            {
                                <p class="fs-14 float-left">Gtia: @oDetalle.producto.garantia</p>
                            }

                            <span class="fas fa-trash-alt float-right" style="cursor:pointer; font-size: 15px;" onclick="borrarDetalle(@oDetalle.idProducto)"></span>
                        </div>
                    </div>
                </div>
            </div>
            <hr id="hrDiv-@oDetalle.idProducto" />
        }
    }
    <hr style="border-top: 1px solid #b5262a;" />
    <div class="row">
        <div class="col-12 col-sm-10 col-lg-12 col-xl-10 text-center">
            <p class="p-t-6">CLIENTE: <strong class="text-left fs-17 pCliente" id="@oVenta.idCliente">@oVenta.cliente.apellido @oVenta.cliente.nombre &nbsp;&nbsp;&nbsp;</strong></p>
        </div>
        <div class="col-4 offset-4 col-sm-2 offset-sm-0 col-lg-4 offset-lg-4 col-xl-2 offset-xl-0">
            <div class="btn-group w-full" role="group">
                <button type="button" class="btn btn-outline-primary" style="width:100%" onclick="_PopUpBuscarCliente()"><i class="fas fa-share"></i></button>
                <button type="button" class="btn btn-outline-danger" style="width:100%" onclick="BorrarCliente()"><i class="fas fa-times-circle"></i></button>
            </div>
        </div>
        
        


    </div>
    <hr style="border-top: 1px solid #b5262a;" />
    <div class="row ">
        <div class="col-12">
            <p id="" class="text-right fs-20" style="color:#000">Total:$ <i id="iTotal">@Math.Round(total,0)</i></p>
        </div>
    </div>
    <hr style="border-top: 1px solid #b5262a;" />
    <div class="row text-center">
        <div class="col-12 col-sm-12">
            <form method="post" action="@Url.Action("GenerarVenta", "Venta")">
                <button id="btnGenerarVenta" type="submit" class="btn btn-dark w-100">Generar venta</button>
            </form>
        </div>
    </div>
</div>

<div id="div-popup-BuscarCliente"></div>

    <script>

        function borrarDetalle(idProducto) {
            var url = "@Url.Action("borrarDetalle", "Venta")";
            var data = { idProducto: idProducto };
            $.post(url, data).done(function (data) {
                if (data == "true") {
                    var stockActual = $('#iSpan-' + idProducto).text();
                    var stockDescontar = $('#i-cant-' + idProducto).text();
                    var stockEstimado = parseInt(stockActual) + parseInt(stockDescontar);
                    var precioDescontar = parseFloat($('#iCostoGrupal-' + idProducto).text());
                    var precioTotal = parseFloat($('#iTotal').text());
                    var decimales = $('#iCostoGrupal-' + idProducto).text().split(',');
                    $('#iSpan-' + idProducto).text(stockEstimado);
                    $('#div-carrito-' + idProducto).remove();
                    $('#hrDiv-' + idProducto).remove();
                    $('#iTotal').text(parseFloat(precioTotal - precioDescontar));
                    if (stockEstimado == 0) {
                        $('#iSpan-' + idProducto).css({ color: "red" });
                    } else {
                        $('#iSpan-' + idProducto).css({ color: "" });
                    }
                } else
                {
                    swal("Ocurrió un error", "Se produjo un error al intentar agregar un producto al carrito", "error");
                }
            });
        }

        function _PopUpBuscarCliente() {

            var url = "@Url.Action("_PopUpBuscarCliente", "Cliente")";
            var data = {};
            $.post(url, data).done(function (data) {
                if (data.length > 0) {
                    $('#div-popup-BuscarCliente').html(data);
                    $('#popupBuscarCliente').modal('show');
                }
            });
        }

        function SelecionarCliente(idCliente, apellido, nombre) {
            var url = "@Url.Action("SeleccionarClienteVenta", "Venta")";
            var data = { 'oCliente.idCliente': idCliente, 'oCliente.apellido': apellido, 'oCliente.nombre': nombre };
            $.post(url, data).done(function (data) {
                $('.pCliente').removeAttr('id');
                $('.pCliente').attr('id', data.idCliente);
                $('#' + data.idCliente).html(data.apellido + " " + data.nombre + " &nbsp;&nbsp;&nbsp;");
                $('#popupBuscarCliente').modal('toggle');
            });

        }

        function BorrarCliente() {
            var url = "@Url.Action("SeleccionarClienteVenta", "Venta")";
            var data = { 'oCliente.idCliente': 0, 'oCliente.apellido': "", 'oCliente.nombre': "" };
            $.post(url, data).done(function (data) {
                $('.pCliente').removeAttr('id');
                $('.pCliente').attr('id', data.idCliente);
                $('#' + data.idCliente).html(data.apellido + " " + data.nombre + " &nbsp;&nbsp;&nbsp;");
            });

        }

    </script>