softcomputacion/Models/reparacion.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace softcomputacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reparacion
    {
        public int idReparacion { get; set; }
        public System.DateTime fecha { get; set; }
        public int idEstado { get; set; }
        public int idCliente { get; set; }
        public int idUsuario { get; set; }
        public string observaciones { get; set; }
        public string producto { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual estado estado { get; set; }
        public virtual usuario usuario { get; set; }
    }
}

softcomputacion/Controllers/ReparacionController.cs
using PagedList;
using softcomputacion.Models;
using softcomputacion.Servicios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace softcomputacion.Controllers
{
    public class ReparacionController : Controller
    {
        // GET: Reparacion
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ListarReparaciones(int nroPagina = 1, int tamañoPagina = 10, bool paginacion = false)
        {
            try
            {
                usuario oUsuario = (usuario)Session["Usuario"];
                if (oUsuario == null)
                {
                    Session.Clear();
                    return RedirectToAction("Index", "Home");
                }
                srvUsuario sUsuario = new srvUsuario();
                ViewBag.Ususarios = sUsuario.ObtenerUsuarios();
                srvEstado sEstado = new srvEstado();
                ViewBag.Estados = sEstado.ObtenerEstados("REPARACION");
                List<reparacion> lstReparaciones = (List<reparacion>)Session["lstReparaciones"];
                if (lstReparaciones == null || lstReparaciones.Count == 0 || paginacion == false)
                {
                    srvReparacion sReparacion = new srvReparacion();
                    lstReparaciones = sReparacion.ObtenerReparaciones();
                    Session["lstReparaciones"] = lstReparaciones;
                }
                ViewBag.filtros = ";;;";
                PagedList<reparacion> ModelReparaciones = new PagedList<reparacion>(lstReparaciones.ToList(), nroPagina, tamañoPagina);
                return View(ModelReparaciones);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error", new { stError = "Se produjo un error al intentar obtener los datos del servidor." });
            }
        }
        [HttpPost]
        public ActionResult ListarReparaciones(int idReparacion = 0, int idUsuario = 0, int idEstado = 0, string stCliente = "")
        {
            try
            {
                ViewBag.filtros = idReparacion + ";" + idUsuario + ";" + idEstado + ";" + stCliente;
                usuario oUsuario = (usuario)Session["Usuario"];
                if (oUsuario == null)
                {
                    Session.Clear();
                    return RedirectToAction("Index", "Home");
                }
                srvReparacion sReparacion = new srvReparacion();
                List<reparacion> lstReparaciones;
                srvUsuario sUsuario = new srvUsuario();
                ViewBag.Ususarios = sUsuario.ObtenerUsuarios();
                srvEstado sEstado = new srvEstado();
                ViewBag.Estados = sEstado.ObtenerEstados("REPARACION");
                lstReparaciones = sReparacion.ObtenerReparaciones(idReparacion, idUsuario, idEstado, stCliente);
                Session["lstReparaciones"] = lstReparaciones;
                PagedList<reparacion> ModelReparaciones = new PagedList<reparacion>(lstReparaciones.ToList(), 1, 10);
                return View(ModelReparaciones);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error", new { stError = "Se produjo un error al intentar obtener los datos del servidor." });
            }
        }
        public ActionResult Reparacion()
        {
            try
            {
                usuario oUsuario = (usuario)Session["Usuario"];
                if (oUsuario == null || oUsuario.idTipoUsuario != 2)
                {
                    Session.Clear();
                    return RedirectToAction("Index", "Home");
                }
                ViewBag.fecha = System.DateTime.Now.Date;
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error", new { stError = "Se produjo un error al intentar obtener los datos del servidor." });
            }

        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Reparacion(int idProducto)
        {
            try
            {
                usuario oUsuario = (usuario)Session["Usuario"];
                if (oUsuario == null || oUsuario.idTipoUsuario != 2)
                {
                    Session.Clear();
                    return RedirectToAction("Index", "Home");
                }
                srvCategoria sCategoria = new srvCategoria();
                ViewBag.lstCategorias = sCategoria.ObtenerCategorias();
                srvProveedor sProveedor = new srvProveedor();
                ViewBag.lstProveedores = sProveedor.ObtenerProveedores();
                srvProducto sProducto = new srvProducto();
                ViewBag.oProducto = sProducto.ObtenerProducto(idProducto);
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error", new { stError = "Se produjo un error al intentar obtener los datos del servidor." });
            }

        }
    }
}

softcomputacion/Views/Reparacion/ListarReparaciones.cshtml
@{
    ViewBag.Title = "Listar reparaciones";
    Layout = "~/Views/Shared/_UsuarioLogueado.cshtml";
    softcomputacion.Models.usuario oUsuario = (softcomputacion.Models.usuario)Session["Usuario"];
    List<softcomputacion.Models.usuario> lstUsuario = (List<softcomputacion.Models.usuario>)ViewBag.Ususarios;
    List<softcomputacion.Models.estado> lstEstado = (List<softcomputacion.Models.estado>)ViewBag.Estados;
    
    string[] filtros = ViewBag.filtros.Split(';');

}
@model PagedList.IPagedList<softcomputacion.Models.reparacion>
@using PagedList.Mvc;

<br />
<br />
<div class="container-fluid">
    <div class="row">
        <div class="col-12 text-center">
            <h2>Reparaciones</h2>
        </div>
    </div>
    <hr style="border-top: 2px solid #b5262a;" />

    <div class="row">
        <div class="col-12 col-lg-12">
            <div class="row">
                <div class="col-12 offset-xl-1 col-xl-10">
                    @* Form de busqueda *@
                    <form method="post" action="@Url.Action("ListarReparaciones", "Reparacion")" autocomplete="off">
                        <div class="row">
                            <div class="col-12 col-md-3 col-lg-2">
                                <div class="wrap-input100 m-b-20">
                                    <input class="input100" type="text" name="idReparacion" id="codigo" placeholder="Código" value="@filtros[0]">
                                </div>
                            </div>
                            <div class="col-12 col-md-3 col-lg-2">
                                <div class="wrap-input100 m-b-20">
                                    <input class="input100" type="text" name="stCliente" id="stCliente" placeholder="Cliente" value="@filtros[3]">
                                </div>
                            </div>

                            <div class="col-12 col-md-3 col-lg-3">
                                <div class="wrap-input100 ¡ m-b-20" data-validate="">
                                    <select id="select-Usuario" class="form-control input100" style="border:0px; height: 55px;" name="idUsuario">
                                        <option selected value="0">Usuario</option>

                                        @foreach (softcomputacion.Models.usuario oUsu in lstUsuario)
                                        {
                                            if (oUsu.idUsuario.ToString() == filtros[1])
                                            {
                                                <option selected value="@oUsu.idUsuario">@oUsu.apellido, @oUsu.nombre</option>
                                            }
                                            else
                                            {
                                                <option value="@oUsu.idUsuario">@oUsu.apellido, @oUsu.nombre</option>
                                            }

                                        }
                                    </select>
                                </div>
                            </div>
                            <div class="col-12 col-md-3 col-lg-3">
                                <div class="wrap-input100 ¡ m-b-20" data-validate="">
                                    <select id="select-Usuario" class="form-control input100" style="border:0px; height: 55px;" name="idUsuario">
                                        <option selected value="0">Estado</option>

                                        @foreach (softcomputacion.Models.estado oEst in lstEstado)
                                        {
                                            if (oEst.idEstado.ToString() == filtros[2])
                                            {
                                                <option selected value="@oEst.idEstado">@oEst.nombre</option>
                                            }
                                            else
                                            {
                                                <option value="@oEst.idEstado">@oEst.nombre</option>
                                            }

                                        }
                                    </select>
                                </div>
                            </div>


                            <div class="col-12 col-md-12 col-lg-1">
                                <div class="container-login100-form-btn m-b-20">
                                    <button class="login100-form-btn fs-22" style="height:56px;" type="submit">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="col-12 col-md-12 col-lg-1">
                                <div class="container-login100-form-btn m-b-20">
                                    <button class="btn fs-22 btn-dark w-full" style="height:56px;" type="button" onclick="location.href='@Url.Action("Reparacion","Reparacion")'">
                                        <i class="fas fa-plus"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>



            <hr style="border-top: 1px solid #b5262a;" />
            <br />
        </div>
        <div class="row container-fluid">
            <!--Lista de Reparaciones-->

            <div class="m-b-15 col-12 offset-xl-1 col-xl-10">
                @{
                    string stFechaHs = "";
                    foreach (var oReparacion in Model)
                    {
                        stFechaHs = oReparacion.fecha.Day.ToString().PadLeft(2, '0') + "/" + oReparacion.fecha.Month.ToString().PadLeft(2, '0') + "/" + oReparacion.fecha.Year;
                        
                        
                        <div class="row">
                            <div class="col-12 p-b-5 p-t-10 item-lista-venta" style="text-align:left;" onclick="window.open('@Url.Action("VistaReparacion","Reparacion", new { idReparacion = oReparacion.idReparacion})')">
                                <div class="row">

                                    <div class="col-12 col-sm-3 col-md-1 col-lg-1 col-xl-1 p-l-5 p-r-5">
                                        <p class="login100-form-title fs-18 p-l-5 text-center text-sm-left">
                                            <span>Nro: @oReparacion.idReparacion</span>
                                        </p>
                                        <p class="text-center text-sm-left @softcomputacion.Servicios.clsMetodosGenericos.ObtenerColorEstadoReparacion(oReparacion.idEstado) text-uppercase"><strong>@oReparacion.estado.nombre</strong></p>
                                    </div>
                                    <div class="col-12 col-sm-3 col-md-3 col-lg-2 col-xl-2 p-l-5 p-r-5">
                                        <p class="login100-form-title fs-18 p-l-5 text-center">
                                            <span>@stFechaHs</span>
                                        </p>
                                    </div>
                                    <div class="col-12 col-sm-6 col-md-5 col-lg-5 col-xl-4 p-l-5 p-r-5">
                                        <p class="login100-form-title fs-18 p-l-5 text-center text-sm-left">
                                            <span>@oReparacion.cliente.nombre, @oReparacion.cliente.apellido</span>
                                        </p>
                                    </div>
                                    <div class="col-12 col-sm-12 col-md-2 col-lg-3 col-xl-4 p-l-5 p-r-5">
                                        <p class="login100-form-title fs-18 p-l-5 text-center text-lg-left">
                                            @oReparacion.producto
                                        </p>
                                    </div>
                                </div>
                            </div>

                            <div class="col-12">
                                <hr class="m-t-0 m-b-0" />
                            </div>
                        </div>
                    }
                }
            </div>
        </div>

        <div class="row container-fluid text-center">
            <div id="div-paginacion" class="col-12">
                @Html.PagedListPager(Model, nroPagina => Url.Action("ListarReparaciones", "Reparacion", new { nroPagina, tamañoPagina = Model.PageSize, paginacion = true }), new PagedListRenderOptions() { ClassToApplyToFirstListItemInPager = null, ClassToApplyToLastListItemInPager = null, UlElementClasses = new[] { "pagination", "justify-content-center" }, LiElementClasses = new[] { "page-item" } })
            </div>
            <div class="col-12">
                @Model.FirstItemOnPage a @Model.LastItemOnPage reparaciones de un total de @Model.TotalItemCount reparaciones.
            </div>
        </div>
    </div>
</div>

softcomputacion/Views/Reparacion/Reparacion.cshtml
@{
    ViewBag.Title = "Reparacion";
    Layout = "~/Views/Shared/_UsuarioLogueado.cshtml";
}
<br /><br />
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-lg-8 offset-lg-2 text-center">
            <h2>Nueva reparación</h2>
        </div>
    </div>
    <hr style="border-top: 2px solid #b5262a;" />
    <div class="row">
        <div class="col-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2">
            <form class="validate-form row" method="post" action="@Url.Action("GuardarModificarReparacion", "Reparacion")" autocomplete="off">
                @Html.AntiForgeryToken()
                <input class="d-none" type="text" id="idCliente" name="oReporte.idCliente">
                <div class="col-12 col-md-12">
                    <div class="row">
                        <div class="col-12 col-sm-10 col-lg-12 col-xl-10 text-center">
                            <p class="p-t-6">CLIENTE: <strong class="text-left fs-17 pCliente" id="">Cliente &nbsp;&nbsp;&nbsp;</strong></p>
                        </div>
                        <div class="col-4 offset-4 col-sm-2 offset-sm-0 col-lg-4 offset-lg-4 col-xl-2 offset-xl-0">
                            <div class="btn-group w-full" role="group">
                                <button type="button" class="btn btn-outline-primary" style="width:100%" onclick="_PopUpBuscarCliente()"><i class="fas fa-share"></i></button>
                                <button type="button" class="btn btn-outline-danger" style="width:100%" onclick="BorrarCliente()"><i class="fas fa-times-circle"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-12">
                    <label for="frmNombre">Producto</label>
                    <div class="wrap-input100 validate-input m-b-20" data-validate="Garantia">
                        <input class="input100" type="text" name="oReporte.producto" placeholder="Producto">
                    </div>
                </div>

                <div class="col-12">
                    <label for="frmNombre">Observación</label>
                    <div class="wrap-input100 m-b-20">
                        <textarea class="input100 p-t-15" style="height:100px" type="text" name="oReparacion.observacion" placeholder="Observacion"></textarea>
                    </div>
                </div>



                <!--btns-->
                <div class="col-12 col-md-10 offset-md-1 col-lg-10 offset-lg-1">
                    <div class="container-login100-form-btn m-t-20 m-b-30">
                        <button id="btnGuardar" type="submit" class="btn btn-success fs-22" style="width:100%">Guardar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div id="div-popup-BuscarCliente"></div>



@section scripts{






    
    <script>
         function _PopUpBuscarCliente() {

            var url = "@Url.Action("_PopUpBuscarCliente", "Cliente")";
            var data = {};
            $.post(url, data).done(function (data) {
                if (data.length > 0) {
                    $('#div-popup-BuscarCliente').html(data);
                    $('#popupBuscarCliente').modal('show');
                }
            });
        }

        function SelecionarCliente(idCliente, apellido, nombre) {
            console.log(idCliente, apellido, nombre);
            $('.pCliente').removeAttr('id');
            $('.pCliente').attr('id', idCliente);
            $('#idCliente').val(idCliente);
            $('#' + idCliente).html(apellido + " " + nombre + " &nbsp;&nbsp;&nbsp;");
            $('#popupBuscarCliente').modal('toggle');

        }

        function BorrarCliente() {
            $('#idCliente').val('');
            $('.pCliente').removeAttr('id');
            $('.pCliente').attr('id', data.idCliente);
            $('#' + data.idCliente).html(data.apellido + " " + data.nombre + " &nbsp;&nbsp;&nbsp;");

        }
    </script>
}